#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#radar o phpstan
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
  echo "Opa! Deu ruim aqui com o PHPSTAN. Arrume antes de continuar...";
  exit 1;
fi;

# formata dos os arquivos alterados
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
  ./vendor/bin/pint "${FILE}" > /dev/null &1;
  git add "{$FILE}"
done;

exit 0;
